//Оболочка отображаемых страниц и компонентов

import type { Metadata } from 'next'
// import { Nunito } from 'next/font/google'
// import '../globals.css'
import { Header } from '@/shared/components'
import { Suspense } from 'react'
// import { Header } from '@/components/shared/header'

// const nunito = Nunito({
//     subsets: ['cyrillic'],
//     variable: '--font-nunito',
//     weight: ['400', '500', '600', '700', '800', '900'],
// })

export const metadata: Metadata = {
    title: 'Next Pizza | Главная',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    modal
}: Readonly<{
    children: React.ReactNode
    modal: React.ReactNode
}>) {
    return (
        // <html lang='en'>
        //     <body className={nunito.className}>
        <main className='min-h-screen'>
            <Suspense>
                <Header />
            </Suspense>
            {children}
            {modal}
        </main>
        //         </body>
        //     </html>
    )
}
