//Основная оболочка всего приложения

import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'//этот css будет распространяться и на подчинённые оболочки(лэйауты)
import Providers from '@/utils/providers'
// import { Header } from '@/components/shared/header'
//import { Toaster } from 'react-hot-toast';//импортировать Toaster для глобального использования

const nunito = Nunito({
    subsets: ['cyrillic'],
    variable: '--font-nunito',
    weight: ['400', '500', '600', '700', '800', '900'],
})

//В основной оболочке не должно быть Метаданных
// export const metadata: Metadata = {
//     title: 'Next Pizza | Главная',
//     description: 'Generated by create next app',
// }

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            {/* Подключим иконку */}
            <head>
                <link data-rh="true" rel="icon" href="/logo.png" />
            </head>
            <body className={nunito.className}>
                <Providers>{children}</Providers>
                {/* <Toaster /> */}
            </body>
        </html>
    )
}
